### ISSUE TITLE
Customizing change animations in Objective C

### ISSUE THREAD

**Issue by ortizroberto** [3lvis/DATASource#108]
Hi Elvis!

I'm trying to customize animations in Objective C, but I can't get to access the dictionary for animations. How I accomplish this?

I love this library BTW.

**Comment by 3lvis** [comment]
Hi Roberto, could you try creating a Swift file with the same name as your objective c class and make an extension of your controller in the Swift file. Here you should be able to edit the animations.

Let me know how it goes :)

**Comment by ortizroberto** [comment]
I made a subclass of my tableview in Swift and created all the custom animations there.

**Comment by 3lvis** [comment]
👏
