### ISSUE TITLE
NSRangeException exception in NSFetchedResultsChangeUpdate event of NSFetchedResultsController

### ISSUE THREAD

**Issue by batjo** [3lvis/DATASource#111]
For some background related to this issue please see: https://stackoverflow.com/questions/11432556/nsrangeexception-exception-in-nsfetchedresultschangeupdate-event-of-nsfetchedres

**Comment by 3lvis** [comment]
Added you as a collaborator as well :)

**Comment by 3lvis** [comment]
Shipped in https://github.com/3lvis/DATASource/releases/tag/7.0.1
