### ISSUE TITLE
UITableVIew swipe trailingSwipeActionsConfigurationForRowAt not working

### ISSUE THREAD

**Issue by mperovic** [3lvis/DATASource#114]
After implementing DATASource on my UITableView new iOS 11 UITableView Swipe action not getting called. Other delegate and datasource are working fine. For example tableView:didSelectRowAt works perfectly.

**Comment by 3lvis** [comment]
Hi @mperovic,

Strange issue. I'll see if I can have a look :)

**Comment by mperovic** [comment]
Just forgot to mention tableView:leadingSwipeActionsConfigurationForRowAt also does not work.

**Comment by mperovic** [comment]
Found what was problem. It was my mistake. Forgot to return true from dataSource:tableView:canEditRowAtIndexPath:
