### ISSUE TITLE
sortDescriptors proposal

### ISSUE THREAD

**Issue by dneykov** [3lvis/DATASource#116]
Hello everyone,

may I suggest computed property just like `predicate` but `sortDescriptors` so you can easily sort your data source. What do you think?

Best regards,
Daniel

**Comment by JpegDev** [comment]
I'm not sure to understand.
sortDescriptors already exist on NSFetchRequest

Ex:
let request: NSFetchRequest = NSFetchRequest<NSFetchRequestResult>(entityName: "Entity")
    request.sortDescriptors = [NSSortDescriptor(key: "title", ascending: true)]
request.predicate = NSPredicate(format: "selected == true")
......

**Comment by dneykov** [comment]
I'm not talking about `NSFetchRequest` but for `DATASource` so you can sort your `tableView` for example when data is already loaded.

**Comment by rlester** [comment]
I ran into this issue as well and opened a PR to fix it: #119 119

**Comment by 3lvis** [comment]
Great job @rlester 👏 🔥
