### ISSUE TITLE
Ability to disable section index

### ISSUE THREAD

**Issue by syky27** [3lvis/DATASource#37]
Hi!
Due the fact that I could not override `func sectionIndexTitlesForTableView(tableView: UITableView) -> [String]?` I forked your repo and create a argument in constructor ti disable section index, because I really dont need one in my app, I twisted it only for Swift UITableView as you can see here: https://github.com/AJTY/DATASource/commit/8fe934ebd44d82712c61ee26ecfa12cd5e4bcdbf

In case this is something you would like to have in your project, you can either think of better way how to do that, or I can get it done for all other usage of DATASource and then I can create pull request.

Let me know, if you want me to help you with this or if you are even interested in it. In case I was doing something wrong and I did not needed to do that to achieve what I wanted, throw on me all the dirt you have.

Thanks Syky.

**Comment by 3lvis** [comment]
@syky27 sending sectionName = `nil` isn't enough?

**Comment by 3lvis** [comment]
Hi Tomas!

I tried and made it work, I found a typo too! So it would be great if you updated to `DATASource 5.0.2` before trying this.

>#### The section grouping is cool, but I don't want the indexes
>
>You can disable the indexes by overwritting the method that generates them and just return an empty list of indexes. Add the `DATASourceDelegate` protocol to your controller then:

```swift
self.dataSource.delegate = self

func sectionIndexTitlesForDataSource(dataSource: DATASource, tableView: UITableView) -> [String] {
    return [String]()
}
```

Added it to the README too: https://github.com/3lvis/DATASource/blob/master/README.md#the-section-grouping-is-cool-but-i-dont-want-the-indexes
