### ISSUE TITLE
Cannot get editActionsForRowAtIndexPath: to work

### ISSUE THREAD

**Issue by syky27** [3lvis/DATASource#41]
Hi! No matter what I do I cannot get this to work. 

```
    override func tableView(tableView: UITableView, editActionsForRowAtIndexPath indexPath: NSIndexPath) -> [UITableViewRowAction]? {
        let block = UITableViewRowAction(style: .Normal, title: "Block") { action, index in
            print("Block")
        }
        let delete = UITableViewRowAction(style: .Default, title: "Delete") { action, index in
            print("Delete")
        }
        return [delete, block]
    }
    
    func dataSource(dataSource: DATASource, tableView: UITableView, canEditRowAtIndexPath indexPath: NSIndexPath) -> Bool {
        return true
    }
    
    func dataSource(dataSource: DATASource, tableView: UITableView, commitEditingStyle editingStyle: UITableViewCellEditingStyle, forRowAtIndexPath indexPath: NSIndexPath) {
    }
```
IMHO you are missing something like this
```
func dataSource(dataSource: DATASource, tableView: UITableView, editActionsForRowAtIndexPath indexPath: NSIndexPath) -> [UITableViewRowAction]?
```

In case not, please correct me.

Thank you!

**Comment by 3lvis** [comment]
Hi Tomas,

Thanks for reporting this issue! I'll have a look at it. :smile:

**Comment by 3lvis** [comment]
@syky27 Hi!

That's a UITableViewDelegate method, DATASource only takes care of the UITableViewDataSource methods.

https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITableViewDelegate_Protocol/#//apple_ref/occ/intfm/UITableViewDelegate/tableView:editActionsForRowAtIndexPath:

Best,

**Comment by 3lvis** [comment]
@syky27 There you go 

https://github.com/3lvis/DATASource/blob/master/DATASourceDelegateTableSwift/ViewController.swift

**Comment by syky27** [comment]
Hi! So I tried to download your example, but after running it on my iPhone it crashes on

```
dyld`dyld_fatal_error:
->  0x12002d088 <+0>: brk    #0x3
```

Is it happening to you also?

**Comment by 3lvis** [comment]
@syky27 wow, this is really weird. Might be something related to your Xcode installation.

**Comment by syky27** [comment]
@3lvis Then I suppose it works for you right? I was trying to run your example because I still cannot get the swiping to work...

I will try to compile my app on my Mac Build Server, Then I will let you know...

Thanks

**Comment by 3lvis** [comment]
![edit](https://cloud.githubusercontent.com/assets/1088217/11856849/0c1ad5a6-a454-11e5-98a8-cf39970e7894.gif)

**Comment by 3lvis** [comment]
![edit2](https://cloud.githubusercontent.com/assets/1088217/11856861/230e347e-a454-11e5-919e-9b8668243409.gif)

**Comment by syky27** [comment]
Hi! So I reinstalled Xcode, and it started to work... One just simply needs to hate how dev. tools from Apple are unstable nowadays....

Thanks for help tho.

**Comment by 3lvis** [comment]
@syky27 :blush:
