### ISSUE TITLE
Handling message when tableview is empty

### ISSUE THREAD

**Issue by guilhermekrz** [3lvis/DATASource#43]
I think that it would be useful to expose some delegate to enable setting custom messages when table view is empty (sorry if this is already possible, but I could not find how). Currently I am using something like this: http://stackoverflow.com/questions/28532926/if-no-table-view-results-display-no-results-on-screen

To get it working here ,while using this pod, I added a new delegate (you can check here: https://github.com/guilhermekrz/DATASource/commit/c94e89dcfe291b105fdc07d408bf1b60a40850de).

However I don't think that this is the best way to expose this. Any ideas?

**Comment by 3lvis** [comment]
Hi @guilhermekrz!

We could have a delegate method on [controllerDidChangeContent](https://github.com/3lvis/DATASource/blob/master/Source/DATASource.swift#L475).

Something like 

```swift
optional func dataSourceDidChangeContent(dataSource: DATASource)
```

Could work. Feel free to add it, or I'll do it later.

**Comment by guilhermekrz** [comment]
Great! I will try here and then create a pull request.
Thanks!
