### ISSUE TITLE
EXC_BAD_ACCESS on tableView.endUpdates()

### ISSUE THREAD

**Issue by ortizroberto** [3lvis/DATASource#47]
Hi, I have been using DATASource for a hile now with Sync, in my project everything works fine in iOS 9, but testing in iOS 8.4 throws an EXC_BAD_ACCESS on ```public func controllerDidChangeContent``` specifically on ```tableView.endUpdates()``` . Could you guide me in what can be wrong? Thanks

**Comment by 3lvis** [comment]
Hi @ortizroberto,

Hard for me to say what's wrong without steps to reproduce. Could you help me with that?

**Comment by ortizroberto** [comment]
@3lvis I just realized it had nothing to do with DATASource. But thank you so much anyway, keep up this good work.

**Comment by 3lvis** [comment]
@ortizroberto Great news! Have an awesome weekend! :beers:
