### ISSUE TITLE
are you aware of any Realm equivalent to DATASource?

### ISSUE THREAD

**Issue by skydivedan** [3lvis/DATASource#48]
Sorry if the wrong forum, as this isn't a problem. 

I've used DATASource in another project and loved it. On a new project, I'm using Realm as the persistent layer. I've seen some things on the Realm side that do things to replicate NSFetchedResultsController. However, I haven't seen anything yet that does as nice a job as DATASource on the Realm side of things. It could be that I'm just not looking in the right place. But if you knew of a Realm equivalent of DATASource, I'd be happy to hear about it.

**Comment by 3lvis** [comment]
Hi Dan! Check out https://redbooth.com/engineering/ios/realmresultscontroller

I haven't tried myself but seems well done. 

Merry Christmas 🎄 :santa:!
