### ISSUE TITLE
Number of sections returns one, even if theres is no objects

### ISSUE THREAD

**Issue by amanbolat** [3lvis/DATASource#68]
I want show custom message when table view is empty, but it always return 1, even if theres is no data.
```
public func numberOfSectionsInTableView(tableView: UITableView) -> Int {
        print(self.fetchedResultsController.sections?.count)
        return self.fetchedResultsController.sections?.count ?? 0
    }
```
But, when i use this function without implementing DATASource, just in my own table, it returns correct count of sections:
```
public func numberOfSectionsInTableView(tableView: UITableView) -> Int {
        print(self.fetchedResultsController.sections?.count)
        return self.fetchedResultsController.sections?.count ?? 0
    }
```
Can't find any explanation for that.

**Comment by 3lvis** [comment]
[Overwriting any `UITableViewDataSource` breaks the functionality of `DATASource`](https://github.com/3lvis/DATASource#uitableviewdatasource), for your use case I would advise you to do something like:

```swift
// In your DATASource declaration
self.source = DATASource(...)
self.source.delegate = self
```

```swift
extension MyController: DATASourceDelegate {
    func dataSourceDidChangeContent(dataSource: DATASource) {
        if self.source.isEmpty {
            // show custom message
        }
    }
}
```

I hope this helps, let me know if this doesn't work and I'll reopen the issue.

**Comment by amanbolat** [comment]
@3lvis Yes, you are right. I'm already using isEmpty variable to show or not show Empty message. However i don't understand why  `numberOfSectionsInTableView ` returns 1?

**Comment by 3lvis** [comment]
@amanbolat I guess that's on your side, please make sure to not overwrite any `UITableViewDataSource` method on your controllers if you're using `DATASource`.
