### ISSUE TITLE
Support of transient property for sectionName

### ISSUE THREAD

**Issue by zarv1k** [3lvis/DATASource#69]
Transient property for sectionName does not supported for now.
When I use 'firstLetter' (transient property) as sectionName in DATASource initializer I got error:
`'Invalid keypath firstLetter passed to setPropertiesToFetch:'`
There is an issue in default implementation of [UIDataSourceTableView.sectionIndexTitlesForTableView:](https://github.com/3lvis/DATASource/blob/master/Source/DATASource%2BUITableViewDataSource.swift#L37). I suppose this method should detect is property transient and should not execute request when property is transient. Or maybe this metnod should notify developer somehow that when using transient property he must implement DATASourceDelegate.sectionIndexTitlesForDataSource: in this case.

**Comment by 3lvis** [comment]
Hi @zarv1k,

Is this even possible with vanilla NSFetchedResultsController? I can't remember been able to make this work. Would you mind sharing a sample code to try it out?

**Comment by zarv1k** [comment]
@3lvis ok, when I have time (probably at evening today) I'll try to modify your TableSwift example for using 'firstLetterOfName' as transient property instead of managed.

**Comment by 3lvis** [comment]
Thanks a lot!

**Comment by Sorix** [comment]
Transient property sorting is very important by my mind, for example if you want to group items by month without storing month in database (only NSDate usually stored).

If Core Data has issues with «COUNT» maybe it will be better to specify var in DATASource configuration (e.g.: var supportTransient: Bool) where we can enable transient support by specifying that after DATASource initialization?

NSFetchedResultsController supports sectioning by transient properties out of the box, it is very strange if DATASource won’t have support of that.

**Comment by 3lvis** [comment]
@Sorix that could be an option. I'm going to play with adding support for this next week.

**Comment by rottajuliano** [comment]
I agree with Sorix, I really needed to sort in daily sections, got stuck while trying to make DATASource support it and now will switch back to NSFetchedResultsController for a while :/

**Comment by henkvanderspek** [comment]
The funny thing is, it worked in 6.0.0 for sure and it crashes in version 6.1.1

**Comment by 3lvis** [comment]
I'll have a closer look this weekend :)

**Comment by henkvanderspek** [comment]
Cool! Thanks

**Comment by 3lvis** [comment]
Doing some spring cleaning, please make a new issue if you still want to do this.
